# Sources : https://styleci.readme.io/docs/getting-started
# Fixers : https://styleci.readme.io/docs/fixers

preset: psr2

risky: false

enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow
    
disabled:
  - align_double_arrow
  - short_array_syntax
    
finder:
    # Tags : exclude, depth, [not-](name, contains, path)
    name:
        - "*.php"
        
    path:
        - "./src"